import type { Metadata } from 'next';
import { Golos_Text } from 'next/font/google';
import './globals.css';
import { Header } from '@/widgets';
import localFont from 'next/font/local';

const golosText = Golos_Text({
  variable: '--font-golos-text',
  subsets: ['latin'],
});

const customFont = localFont({
  src: '../../public/fonts/druktextwidecyr-medium.woff2',
  variable: '--font-druk', // CSS переменная
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${golosText.variable} ${customFont.variable} antialiased h-screen`}
      >
        <Header />
        <main className={'w-full h-full font-druk'}>{children}</main>
      </body>
    </html>
  );
}
